### ISSUE TITLE
是以那种方式添加的开机自启？如何清除？

### ISSUE THREAD

**Issue by h2so0o4** [Push3AX/GrabAccess#1]
你好，问题如上。

**Comment by Push3AX** [comment]
GrabAccess会写入两个注册表条目和两个可执行文件。全删除掉，就清理干净了。
两个注册表分别用于木马自启动和劫持Shift键，路径如下：
\Registry\Machine\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
\Registry\Machine\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sethc.exe
两个可执行文件分别是NativeApp和木马文件，路径如下：
C:\windows\system32\wpbbin.exe
C:\Windows\System32\NTUpdateService.exe

**Comment by h2so0o4** [comment]
> GrabAccess会写入两个注册表条目和两个可执行文件。全删除掉，就清理干净了。 两个注册表分别用于木马自启动和劫持Shift键，路径如下： \Registry\Machine\SOFTWARE\Microsoft\Windows\CurrentVersion\Run \Registry\Machine\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sethc.exe 两个可执行文件分别是NativeApp和木马文件，路径如下： C:\windows\system32\wpbbin.exe C:\Windows\System32\NTUpdateService.exe

非常感谢
